services:
  - type: web
    name: gpt-alpha-squeeze
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ALPACA_KEY_ID
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: ALPACA_API_URL
        value: https://paper-api.alpaca.markets
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: BENZINGA_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
